apps/homepage/urls.py
from django.urls import path
from .views import *

app_name = "homepage"

urlpatterns = [
    path("home/", HomePageView.as_view(), name="home"),
]

apps/main/urls.py
from django.urls import path
from .views.authors.views import (
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
)
from .views.publishers.views import (
    PublisherListView,
    PublisherCreateView,
    PublisherUpdateView,
    PublisherDeleteView,
)
from .views.books.views import (
    BookListView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
)

app_name = "main"

urlpatterns = [
    # AUTHOR URLS
    path("author/list/", AuthorListView.as_view(), name="author_list"),
    path("author/create/", AuthorCreateView.as_view(), name="author_create"),
    path("author/update/<int:pk>/", AuthorUpdateView.as_view(), name="author_update"),
    path("author/delete/<int:pk>/", AuthorDeleteView.as_view(), name="author_delete"),
    #   PUBLISHER URLS
    path("publisher/list/", PublisherListView.as_view(), name="publisher_list"),
    path("publisher/create/", PublisherCreateView.as_view(), name="publisher_create"),
    path(
        "publisher/update/<int:pk>/",
        PublisherUpdateView.as_view(),
        name="publisher_update",
    ),
    path(
        "publisher/delete/<int:pk>/",
        PublisherDeleteView.as_view(),
        name="publisher_delete",
    ),
    #  BOOK URLS
    path("book/list/", BookListView.as_view(), name="book_list"),
    path("book/create/", BookCreateView.as_view(), name="book_create"),
    path("book/update/<int:pk>/", BookUpdateView.as_view(), name="book_update"),
    path("book/delete/<int:pk>/", BookDeleteView.as_view(), name="book_delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.login.urls")),
    path("homepage/", include("apps.homepage.urls")),
    path("main/", include("apps.main.urls")),
    path("user/", include("apps.user.urls")),
]

apps/homepage/models.py
from django.db import models

# Create your models here.

apps/homepage/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic import TemplateView

# Create your views here.


class HomePageView(TemplateView):
    template_name = "index.html"

    @method_decorator(login_required(login_url=reverse_lazy("login:login_view")))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

apps/homepage/templates/index.html
{% extends 'home.html' %}

{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel active" style="background-image: url('{% static 'img/authorBanner.png' %}');">
            <a href="{% url 'main:author_create' %}">Authors <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
        </div>
        <div class="panel" style="background-image: url('{% static 'img/bookBanner.jpg' %}');">
            <a href="{% url 'main:book_create' %}">Books <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
        </div>
        <div class="panel" style="background-image: url('{% static 'img/publisherBanner.jpg' %}');">
            <a href="{% url 'main:publisher_create' %}">Publishers <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
        </div>
        <div class="panel" style="background-image: url('{% static 'img/aboutBanner.jpg' %}');">
            <a href="#">About <i class="fa fa-question-circle" aria-hidden="true"></i></a>
        </div>
    </div>

    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}