apps/homepage/urls.py
from django.urls import path
from .views import *

app_name = "homepage"

urlpatterns = [
    path("home/", HomePageView.as_view(), name="home"),
]

apps/login/urls.py
from django.urls import path
from .views import *

app_name = "login"

urlpatterns = [
    path("", LoginFormView.as_view(), name="login_view"),
    path("logout/", LogoutFormView.as_view(), name="logout_view"),
]

apps/main/urls.py
from django.urls import path
from .views.authors.views import (
    AuthorListView,
    AuthorCreateView,
    AuthorUpdateView,
    AuthorDeleteView,
)
from .views.publishers.views import (
    PublisherListView,
    PublisherCreateView,
    PublisherUpdateView,
    PublisherDeleteView,
)
from .views.books.views import (
    BookListView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
)

app_name = "main"

urlpatterns = [
    # AUTHOR URLS
    path("author/list/", AuthorListView.as_view(), name="author_list"),
    path("author/create/", AuthorCreateView.as_view(), name="author_create"),
    path("author/update/<int:pk>/", AuthorUpdateView.as_view(), name="author_update"),
    path("author/delete/<int:pk>/", AuthorDeleteView.as_view(), name="author_delete"),
    #   PUBLISHER URLS
    path("publisher/list/", PublisherListView.as_view(), name="publisher_list"),
    path("publisher/create/", PublisherCreateView.as_view(), name="publisher_create"),
    path(
        "publisher/update/<int:pk>/",
        PublisherUpdateView.as_view(),
        name="publisher_update",
    ),
    path(
        "publisher/delete/<int:pk>/",
        PublisherDeleteView.as_view(),
        name="publisher_delete",
    ),
    #  BOOK URLS
    path("book/list/", BookListView.as_view(), name="book_list"),
    path("book/create/", BookCreateView.as_view(), name="book_create"),
    path("book/update/<int:pk>/", BookUpdateView.as_view(), name="book_update"),
    path("book/delete/<int:pk>/", BookDeleteView.as_view(), name="book_delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.login.urls")),
    path("homepage/", include("apps.homepage.urls")),
    path("main/", include("apps.main.urls")),
    path("user/", include("apps.user.urls")),
]

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Libreria</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'css/styles-nav.css' %}">
    {% block head %}

    {% endblock %}
  </head>
  <body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <div class="header">
      {% include 'nav-bar.html' %}
    </div>
    {% block content %}

    {% endblock %}
  </body>
</html>

templates/nav-bar.html
<nav class="nav justify-content-center">
  <a class="nav-link active" href="{% url 'homepage:home' %}"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
  <a class="nav-link" href="{% url 'main:author_list' %}"><i class="fa fa-user-circle" aria-hidden="true"></i> Authors</a>
  <a class="nav-link" href="{% url 'main:book_list' %}"><i class="fa fa-book" aria-hidden="true"></i> Books</a>
  <a class="nav-link" href="{% url 'main:publisher_list' %}"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Publishers</a>
  <a class="nav-link" href="#"><i class="fa fa-question-circle" aria-hidden="true"></i> About</a>
  <a class="nav-link" href="{% url 'login:logout_view' %}"><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> LogOut</a>
</nav>