apps/login/urls.py
from django.urls import path
from .views import *

app_name = "login"

urlpatterns = [
    path("", LoginFormView.as_view(), name="login_view"),
    path("logout/", LogoutFormView.as_view(), name="logout_view"),
]

apps/user/urls.py
from django.urls import path
from .views import UserCreateView


app_name = "user"

urlpatterns = [
    path("create/", UserCreateView.as_view(), name="user_create"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.login.urls")),
    path("homepage/", include("apps.homepage.urls")),
    path("main/", include("apps.main.urls")),
    path("user/", include("apps.user.urls")),
]

apps/login/models.py
from django.db import models

# Create your models here.

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy


# Create your views here.
class LoginFormView(LoginView):
    template_name = "login.html"
    success_url = reverse_lazy("homepage:home")

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(self.success_url)
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Iniciar Sesión"
        return context


class LogoutFormView(LogoutView):
    def post(self, request, *args, **kwargs):
        if self.request.method == "POST":
            self.request.session.flush()
            self.request.session.clear_expired()
            return redirect("login:login")
        return super().post(request, *args, **kwargs)

apps/login/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/styles-login.css' %}">
  </head>
  <body>
    <div class="container">
      <h1>Please LogIn</h1>
      <form method="post">
        {% csrf_token %}
        <div class="form-c">
          <input type="text" id="username" name="username" required>
          <label for="username">Username</label>
      </div>
      <div class="form-c">
        <input type="password" id="password" name="password" required>
          <label for="password">Password</label>
      </div>

        <button type="submit" class="btn">LogIn</button>
        <p class="text">Don't have an account? <a href="{% url 'user:user_create' %}">SignUp</a></p>
      </form>
    </div>
    
    <script src="{% static 'js/indexLogin.js' %}"></script>
  </body>
</html>